-- ============================================================
-- StaySync - Initial Database Schema
-- Flyway Migration V1
-- Database: PostgreSQL
-- ============================================================


-- ============================================================
-- 1. HOTELS
-- ============================================================

CREATE TABLE hotels (
    hotel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(150) NOT NULL,
    address VARCHAR(500),
    phone VARCHAR(20),
    email VARCHAR(255),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_hotel_name
        UNIQUE (name)
);


-- ============================================================
-- 2. ROOM TYPES
-- ============================================================

CREATE TABLE room_types (
    room_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),

    base_price NUMERIC(10,2) NOT NULL,

    capacity INTEGER NOT NULL,

    status VARCHAR(30) NOT NULL
        DEFAULT 'ACTIVE',

    created_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_room_type_name
        UNIQUE (name),

    CONSTRAINT chk_room_type_price
        CHECK (base_price > 0),

    CONSTRAINT chk_room_type_capacity
        CHECK (capacity > 0),

    CONSTRAINT chk_room_type_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


-- ============================================================
-- 3. GUESTS
-- ============================================================

CREATE TABLE guests (
    guest_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),

    email VARCHAR(255),
    phone VARCHAR(20),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- 4. ROOMS
-- ============================================================

CREATE TABLE rooms (
    room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    hotel_id BIGINT NOT NULL,
    room_type_id BIGINT NOT NULL,

    room_number VARCHAR(20) NOT NULL,

    floor INTEGER,

    status VARCHAR(30) NOT NULL
        DEFAULT 'AVAILABLE',

    created_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_room_hotel
        FOREIGN KEY (hotel_id)
        REFERENCES hotels(hotel_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_room_type
        FOREIGN KEY (room_type_id)
        REFERENCES room_types(room_type_id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_room_hotel_number
        UNIQUE (hotel_id, room_number),

    CONSTRAINT chk_room_floor
        CHECK (floor IS NULL OR floor >= 0),

    CONSTRAINT chk_room_status
        CHECK (
            status IN (
                'AVAILABLE',
                'OCCUPIED',
                'MAINTENANCE',
                'OUT_OF_SERVICE'
            )
        )
);


-- ============================================================
-- 5. STAFF
-- ============================================================

CREATE TABLE staff (
    staff_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    hotel_id BIGINT NOT NULL,

    name VARCHAR(150) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(20),

    role VARCHAR(50) NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_staff_hotel
        FOREIGN KEY (hotel_id)
        REFERENCES hotels(hotel_id)
        ON DELETE RESTRICT
);


-- ============================================================
-- 6. BOOKINGS
-- ============================================================

CREATE TABLE bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    guest_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,

    check_in TIMESTAMP WITH TIME ZONE NOT NULL,
    check_out TIMESTAMP WITH TIME ZONE NOT NULL,

    price NUMERIC(10,2) NOT NULL,

    status VARCHAR(30) NOT NULL
        DEFAULT 'PENDING',

    created_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_booking_guest
        FOREIGN KEY (guest_id)
        REFERENCES guests(guest_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_booking_room
        FOREIGN KEY (room_id)
        REFERENCES rooms(room_id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_booking_dates
        CHECK (check_out > check_in),

    CONSTRAINT chk_booking_price
        CHECK (price > 0),

    CONSTRAINT chk_booking_status
        CHECK (
            status IN (
                'PENDING',
                'CONFIRMED',
                'CHECKED_IN',
                'CHECKED_OUT',
                'CANCELLED'
            )
        )
);


-- ============================================================
-- 7. PAYMENTS
-- ============================================================

CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id BIGINT NOT NULL,

    amount NUMERIC(10,2) NOT NULL,

    method VARCHAR(30) NOT NULL,

    status VARCHAR(30) NOT NULL
        DEFAULT 'PENDING',

    paid_at TIMESTAMP WITH TIME ZONE,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_booking
        FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_payment_amount
        CHECK (amount > 0),

    CONSTRAINT chk_payment_method
        CHECK (
            method IN (
                'CASH',
                'CARD',
                'UPI',
                'BANK_TRANSFER'
            )
        ),

    CONSTRAINT chk_payment_status
        CHECK (
            status IN (
                'PENDING',
                'SUCCESS',
                'FAILED',
                'REFUNDED'
            )
        )
);


-- ============================================================
-- INDEXES
-- ============================================================

-- Rooms
CREATE INDEX idx_rooms_hotel_id
    ON rooms(hotel_id);

CREATE INDEX idx_rooms_room_type_id
    ON rooms(room_type_id);

CREATE INDEX idx_rooms_status
    ON rooms(status);


-- Staff
CREATE INDEX idx_staff_hotel_id
    ON staff(hotel_id);


-- Bookings
CREATE INDEX idx_bookings_guest_id
    ON bookings(guest_id);

CREATE INDEX idx_bookings_room_id
    ON bookings(room_id);

CREATE INDEX idx_bookings_status
    ON bookings(status);

CREATE INDEX idx_bookings_check_in
    ON bookings(check_in);

CREATE INDEX idx_bookings_check_out
    ON bookings(check_out);


-- Payments
CREATE INDEX idx_payments_booking_id
    ON payments(booking_id);

CREATE INDEX idx_payments_status
    ON payments(status);